# vim: set ts=2 sw=2 ai si et:
---

image: debian:unstable

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths: []

before_script:
  - apt-get update -y
  - apt-get dist-upgrade -y
  - apt-get install -y --install-recommends ansible-lint

stages:
  - test

test:lint:
  stage: test
  script:
    - ansible-lint
