# vim: set ts=2 sw=2 ai si et:
---

- name: backup nodepilot config
  copy:
    src: '/home/{{ nodepilot_user_name }}/.node-pilot/config'
    dest: '/home/{{ nodepilot_user_name }}/.node-pilot/.backup.config.{{ ansible_date_time.iso8601_basic_short }}'
    mode: preserve
    remote_src: yes

- name: enable nodepilot service
  service:
    daemon_reload: true
    name: nodepilot
    enabled: true

- name: restart nodepilot service
  service:
    daemon_reload: true
    name: nodepilot
    state: restarted

- name: enable fstrim.timer
  service:
    name: fstrim.timer
    enabled: yes
    state: started

- name: enable ufw
  ufw:
    state: enabled

- name: restart ufw
  service:
    name: ufw
    enabled: true
    state: restarted
