# vim: set ts=2 sw=2 ai si et:
---

- name: enable nodepilot service
  service:
    name: nodepilot
    enabled: true

- name: enable fstrim.timer
  service:
    name: fstrim.timer
    enabled: yes
    state: started

- name: enable ufw
  ufw:
    state: enabled

- name: restart ufw
  service:
    name: ufw
    enabled: true
    state: restarted
